# Generated by Django 4.1.3 on 2022-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image_pic",
            field=models.ImageField(blank=True, null=True, upload_to="media/profile/"),
        ),
    ]
