# Generated by Django 4.1.3 on 2022-12-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_profile_image_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
    ]
