# Generated by Django 4.1.3 on 2022-12-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
